// symbol index generated by DDOX - do not edit
var symbols = [
{name: "dawg.bloom", kind: "module", path: "./dawg/bloom.html", attributes: []},
{name: "dawg.bloom.BloomFilter", kind: "structdeclaration", path: "./dawg/bloom/BloomFilter.html", attributes: []},
{name: "dawg.bloom.BloomFilter.clear", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.clear.html", attributes: []},
{name: "dawg.bloom.BloomFilter.insert", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.insert.html", attributes: []},
{name: "dawg.bloom.BloomFilter.reset", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.reset.html", attributes: []},
{name: "dawg.bloom.BloomFilter.resize", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.resize.html", attributes: []},
{name: "dawg.bloom.BloomFilter.size", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.size.html", attributes: ["const"]},
{name: "dawg.bloom.BloomFilter.test", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.test.html", attributes: ["const"]},
{name: "dawg.bloom.BloomFilter.this", kind: "functiondeclaration", path: "./dawg/bloom/BloomFilter.this.html", attributes: []},
];
